### ISSUE TITLE
Suggestion: this line is wrong and should be rewritten

### ISSUE THREAD

**Issue by heftberger** [FIAF/fiaf-cataloguing-manual#15]
https://github.com/FIAF/fiaf-cataloguing-manual/blob/a71ffde0c1faf1ebcae0759bf25e368e1ca39d3f/markdown/0057-2.1.2_changes_in_the_format/en.md?plain=1#L17

Please read this carefully!

**Comment by paulduchesne** [comment]
Test issue.
