### ISSUE TITLE
 Introduction: Mistake in text

### ISSUE THREAD

**Issue by paulduchesne** [FIAF/fiaf-cataloguing-manual#64]
Introduction near end, mistake in text

definition of Manifestation - Manifestation information can include a description of whatthe particular Manifestation should ideally contain, regardless of the Items held in thearchive. For example: The original release time of a film is 1:30:00, but the Manifestationheld at the archive is missing footage so is shorter. - shouldn't that read ....but the Item held at the archive is missing footage so is shorter?

**Comment by natashafairbairn** [comment]
This has been done already in branch 87 I think, but not sure if the latter branch is linked to an issue. Will double check

**Comment by paulduchesne** [comment]
Fixed on fb1feb16babb9e125cb990b522878f37298a609d
